name = "nagoda-feedbacks-api"
account_id = "2d433698beceda5a2d764b3bced7e4b2"
main = "src/index.js"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "reviews_db"
database_id = "6d5bdf70-0419-4fb4-88b7-731ffc204d6e"
